work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:wan22_hummingbirdxt_distill}
workspace: ${PRIMUS_WORKSPACE:./output}

modules:
  post_trainer:
    framework: hummingbirdxt
    config: post_trainer.yaml

    # Model to run
    model: wan22.yaml
    overrides:
      stderr_sink_level: DEBUG
      warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
      num_frames: 121
      num_training_frames: 31
