work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:wan22_hummingbirdxt_distill}
workspace: ${PRIMUS_WORKSPACE:./output}

modules:
  post_trainer:
    framework: hummingbirdxt
    config: post_trainer.yaml

    # Model to run
    model: wan22.yaml
    overrides:
      stderr_sink_level: DEBUG
