extends:
  - llama3_base.yaml

tokenizer_type: Llama3Tokenizer
tokenizer_model: meta-llama/Meta-Llama-3.2-1B

ffn_hidden_size: 8192
hidden_size: 2048
num_attention_heads: 16
num_layers: 18
num_query_groups: 4
