work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:llama3_405B-pretrain}
workspace: ./output

modules:
  pre_trainer:
    framework: torchtitan
    config: pre_trainer.yaml

    # model to run
    model: llama3.1_405B-fp8.yaml
    overrides:
      sink_level: null
      file_sink_level: DEBUG
      stderr_sink_level: INFO

      training:
        local_batch_size: 2
        steps: 10

      # profiling:
      #   enable_profiling: true
      #   save_traces_folder: "profile_trace_405B_fp8"
      #   profile_freq: 6

      metrics:
        log_freq: 1

      # model:
      #   n_layers: 20

      optimizer:
        lr: 8.0e-5

      parallelism:
        tensor_parallel_degree: 1

      activation_checkpoint:
        mode: full

      quantize:
        linear:
          float8:
            enable_fsdp_float8_all_gather: true
            precompute_float8_dynamic_scale_for_fsdp: true
            filter_fqns: ["output"]

      primus_turbo:
        enable_primus_turbo: true
        enable_attention_float8: false
