job:
  dump_folder: "./outputs"
  description: "DeepSeek-V3 236B model training"
  print_config: false


model:
  name: "deepseek_v3"
  flavor: "236B"
  hf_assets_path: "deepseek-ai/DeepSeek-V2.5"
  converters:
    - primus_turbo
    - quantize.linear.float8
