patch_primus_pipeline: false

pp_algorithm: "1f1b-interleaved" # "1f1b", "1f1b-interleaved", "zero-bubble", "zbv-formatted", "v-half", "v-min"

communication_method: "async_p2p" # "async_p2p", "batch_p2p"

debug_scheduler_table: false

offload: false
